version: "3.8"

services:
  frontend:
    build: ./public
    ports:
      - "3000:3000"
#    volumes:
#      - ./public:/app
#      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend

  backend:
    build: ./server
    ports:
      - "5000:5000"
#    volumes:
#      - ./server:/app
 #     - /app/node_modules
    environment:
      - MONGO_URL=mongodb://mongo:27017/chat
      - PORT=5000
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: chat_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
    networks:
      - default

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot-etc:/etc/letsencrypt
      - ./certbot-var:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 1; done'"
    networks:
      - default

volumes:
  mongo_data:
  certbot-etc:
  certbot-var:
