name: Deploy to Stage

on:
  push:
    branches:
      - stage

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: 🧪 SSH & Deploy to Stage Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.STAGE_HOST }}
          username: ${{ secrets.STAGE_USER }}
          key: ${{ secrets.STAGE_SSH_KEY }}
          script: |
            cd /home/ubuntu/chat-app
            git pull origin stage
            docker-compose down
            docker-compose up -d --build
